columns:
  - lh_0_x: float64
  - lh_0_y: float64
  - lh_0_z: float64
  - lh_1_x: float64
  - lh_1_y: float64
  - lh_1_z: float64
  - lh_2_x: float64
  - lh_2_y: float64
  - lh_2_z: float64
  - lh_3_x: float64
  - lh_3_y: float64
  - lh_3_z: float64
  - lh_4_x: float64
  - lh_4_y: float64
  - lh_4_z: float64
  - lh_5_x: float64
  - lh_5_y: float64
  - lh_5_z: float64
  - lh_6_x: float64
  - lh_6_y: float64
  - lh_6_z: float64
  - lh_7_x: float64
  - lh_7_y: float64
  - lh_7_z: float64
  - lh_8_x: float64
  - lh_8_y: float64
  - lh_8_z: float64
  - lh_9_x: float64
  - lh_9_y: float64
  - lh_9_z: float64
  - lh_10_x: float64
  - lh_10_y: float64
  - lh_10_z: float64
  - lh_11_x: float64
  - lh_11_y: float64
  - lh_11_z: float64
  - lh_12_x: float64
  - lh_12_y: float64
  - lh_12_z: float64
  - lh_13_x: float64
  - lh_13_y: float64
  - lh_13_z: float64
  - lh_14_x: float64
  - lh_14_y: float64
  - lh_14_z: float64
  - lh_15_x: float64
  - lh_15_y: float64
  - lh_15_z: float64
  - lh_16_x: float64
  - lh_16_y: float64
  - lh_16_z: float64
  - lh_17_x: float64
  - lh_17_y: float64
  - lh_17_z: float64
  - lh_18_x: float64
  - lh_18_y: float64
  - lh_18_z: float64
  - lh_19_x: float64
  - lh_19_y: float64
  - lh_19_z: float64
  - lh_20_x: float64
  - lh_20_y: float64
  - lh_20_z: float64
  - rh_0_x: float64
  - rh_0_y: float64
  - rh_0_z: float64
  - rh_1_x: float64
  - rh_1_y: float64
  - rh_1_z: float64
  - rh_2_x: float64
  - rh_2_y: float64
  - rh_2_z: float64
  - rh_3_x: float64
  - rh_3_y: float64
  - rh_3_z: float64
  - rh_4_x: float64
  - rh_4_y: float64
  - rh_4_z: float64
  - rh_5_x: float64
  - rh_5_y: float64
  - rh_5_z: float64
  - rh_6_x: float64
  - rh_6_y: float64
  - rh_6_z: float64
  - rh_7_x: float64
  - rh_7_y: float64
  - rh_7_z: float64
  - rh_8_x: float64
  - rh_8_y: float64
  - rh_8_z: float64
  - rh_9_x: float64
  - rh_9_y: float64
  - rh_9_z: float64
  - rh_10_x: float64
  - rh_10_y: float64
  - rh_10_z: float64
  - rh_11_x: float64
  - rh_11_y: float64
  - rh_11_z: float64
  - rh_12_x: float64
  - rh_12_y: float64
  - rh_12_z: float64
  - rh_13_x: float64
  - rh_13_y: float64
  - rh_13_z: float64
  - rh_14_x: float64
  - rh_14_y: float64
  - rh_14_z: float64
  - rh_15_x: float64
  - rh_15_y: float64
  - rh_15_z: float64
  - rh_16_x: float64
  - rh_16_y: float64
  - rh_16_z: float64
  - rh_17_x: float64
  - rh_17_y: float64
  - rh_17_z: float64
  - rh_18_x: float64
  - rh_18_y: float64
  - rh_18_z: float64
  - rh_19_x: float64
  - rh_19_y: float64
  - rh_19_z: float64
  - rh_20_x: float64
  - rh_20_y: float64
  - rh_20_z: float64
  - label: object

target_column: label
